appId: com.vblast.flipaclip
---
- launchApp: com.vblast.flipaclip
- tapOn: "Settings"
- takeScreenshot: "../baseline/menu"
- tapOn: "App Settings"
- takeScreenshot: "../baseline/settings"
- scroll
- takeScreenshot: "../baseline/settings-1"
- tapOn: "Back"
- tapOn: "Accounts"
- takeScreenshot: "../baseline/account"
- tapOn: "Back"
- tapOn: "About"
- takeScreenshot: "../baseline/about"