appId: com.vblast.flipaclip
tags:
  - smoke
  - prod
---
- launchApp:
    clearState: true
- runFlow: "../features/welcome-flow/happy-path.yaml"
- runFlow: "../features/welcome-flow/discover-path.yaml"
- runFlow: "../features/welcome-flow/skip-path.yaml"
- runFlow: "../features/welcome-flow/home-path.yaml"
- runFlow: "../features/settings/disable-splash-animation.yaml"
- runFlow: "../features/settings/override-movies.yaml"
- runFlow: "../features/settings/change-layout.yaml"
- runFlow: "../features/account/login-flipaclip-account.yaml"
- runFlow: "../features/account/login-youtube.yaml"
- runFlow: "../features/project/create-project.yaml"
- runFlow: "../features/api/load-audio-library.yaml"
- runFlow: "../features/api/load-actors.yaml"
- runFlow: "../features/project/make-movie-layout-1.yaml"
- runFlow: "../features/settings/change-layout.yaml"
- runFlow: "../features/project/make-movie-layout-2.yaml"
- runFlow: "../features/project/copy-delete-project.yaml"
- runFlow: "../features/project/search-project.yaml"
- runFlow: "../features/movie/delete-movie.yaml"
- runFlow: "../features/api/load-discover.yaml"
- runFlow: "../features/api/load-watch.yaml"
- runFlow: "../features/subscription/load-paywall.yaml"
