executionOrder:
  continueOnFailure: true
  flowsOrder:
    - 00-welcome-flow
    - 01-enable-new-flipaclip
    - 02-disable-splash
    - 03-create-project-layout-1
    - 04-make-movie-layout-1
    - 05-create-project-layout-2
    - 06-make-movie-layout-2
    - 07-create-project-layout-3
    - 08-make-movie-layout-3
    - 09-load-discover
    - 10-load-audio-library
    - 11-load-actors
    - 12-delete-movie
    - 13-load-paywall
    - 14-load-ad
    - 15-edit-project
    - 16-login-flipaclip-account
    - 17-logout-flipaclip-account
    - 18-search-project